### ISSUE TITLE
CXenForo.php on line 289

### ISSUE THREAD

**Issue by superthin** [lairdshaw/fups#6]
When I scrap a XenForo board, this is error:
![Selection_002](https://user-images.githubusercontent.com/3869829/60478455-f7f75400-9cac-11e9-95aa-9c45e97342e8.png)

**Comment by lairdshaw** [comment]
Fixed in commit 469b5c489939723a633fb22711625d5d24f32f1a. This forum adds in a &lt;span&gt; that I hadn't seen before and hadn't accounted for. Not sure whether it's part of a custom skin or configurable in core XenForo code, but I added support for it anyway. Also added support for stripping the Vietnamese word "lúc" out of date-times before trying to parse them.

By the way, I notice that in your settings you'd set Forum IDs to 358 - this is probably a bad idea as it will cause FUPS to try to scrape that entire forum (in addition to scraping the posts of the user with the ID that you entered), and that forum seems to have tens of thousands of posts in it...
